"""PostgreSQL access layer.

Every price, stock level, order and saved chat goes through these functions;
none of it is ever generated by the LLM. Connection settings come from .env
(DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD).
"""

import json
import os
import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb
from dotenv import load_dotenv

load_dotenv()

DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5432"),
    "dbname": os.getenv("DB_NAME", "glowcare"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", "postgres"),
}


def get_connection():
    """Open a connection that returns rows as dicts."""
    return psycopg.connect(**DB_CONFIG, row_factory=dict_row)


def get_product_by_name(name: str):
    """First product whose name contains `name` (case-insensitive), or None."""
    query = "SELECT * FROM products WHERE name ILIKE %s LIMIT 1;"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (f"%{name}%",))
            row = cur.fetchone()
            return dict(row) if row else None


def get_product_price(name: str):
    product = get_product_by_name(name)
    if not product:
        return None
    return {"price": float(product["price"]), "currency": product["currency"]}


def get_product_availability(name: str):
    product = get_product_by_name(name)
    if not product:
        return None
    return {
        "availability": product["availability"],
        "stock_quantity": product["stock_quantity"],
    }


def get_all_products():
    """Id, name and ingredients of every product (a short list, used for name matching).
    """
    query = "SELECT product_id, name, ingredients FROM products ORDER BY product_id;"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query)
            return [dict(r) for r in cur.fetchall()]


def get_product_by_id(product_id: str):
    query = "SELECT * FROM products WHERE product_id = %s;"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (product_id,))
            row = cur.fetchone()
            return dict(row) if row else None


def get_order_status(order_id: str):
    """An order with its line items, or None if the order number doesn't exist."""
    order_query = "SELECT * FROM orders WHERE order_id = %s;"
    items_query = """
        SELECT oi.quantity, oi.price_at_purchase, p.name AS product_name
        FROM order_items oi
        JOIN products p ON p.product_id = oi.product_id
        WHERE oi.order_id = %s;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(order_query, (order_id,))
            order = cur.fetchone()
            if not order:
                return None
            cur.execute(items_query, (order_id,))
            items = cur.fetchall()
            return {
                "order_id": order["order_id"],
                "status": order["status"],
                "total_amount": float(order["total_amount"]),
                "items": [dict(i) for i in items],
            }


def create_conversation(customer_id: int = None, channel: str = "web") -> int:
    query = "INSERT INTO conversations (customer_id, channel) VALUES (%s, %s) RETURNING conversation_id;"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (customer_id, channel))
            conversation_id = cur.fetchone()["conversation_id"]
            conn.commit()
            return conversation_id


ESCALATION_STATUSES = ("pending", "in_progress", "resolved")


def get_open_escalation(conversation_id: int):
    """Most recent unresolved escalation of a chat, or None."""
    query = """
        SELECT * FROM escalations
        WHERE conversation_id = %s AND status <> 'resolved'
        ORDER BY created_at DESC LIMIT 1;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (conversation_id,))
            row = cur.fetchone()
            return dict(row) if row else None


def create_escalation(conversation_id: int, reason: str, priority: str = "normal",
                      customer_message: str = None) -> int:
    """Create an escalation, mark the chat as escalated, and return the new id."""
    insert = """
        INSERT INTO escalations (conversation_id, reason, priority, customer_message)
        VALUES (%s, %s, %s, %s) RETURNING escalation_id;
    """
    mark = "UPDATE conversations SET status = 'escalated' WHERE conversation_id = %s;"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(insert, (conversation_id, reason, priority, customer_message))
            escalation_id = cur.fetchone()["escalation_id"]
            cur.execute(mark, (conversation_id,))
            conn.commit()
            return escalation_id


PRIORITY_RANK = {"low": 0, "normal": 1, "high": 2}


def raise_escalation_priority(escalation_id: int, priority: str, reason: str,
                              customer_message: str):
    """Raise an open case's priority and append the new reason and customer message."""
    query = """
        UPDATE escalations
        SET priority = %s,
            reason = reason || ' + ' || %s,
            customer_message = COALESCE(customer_message || E'\n---\n', '') || %s
        WHERE escalation_id = %s;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (priority, reason, customer_message, escalation_id))
            conn.commit()


def list_escalations(status: str = None):
    """Escalations, most urgent first; optionally only one status."""
    query = """
        SELECT * FROM escalations
        {where}
        ORDER BY CASE priority WHEN 'high' THEN 0 WHEN 'normal' THEN 1 ELSE 2 END,
                 created_at;
    """.format(where="WHERE status = %s" if status else "")
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (status,) if status else None)
            return [dict(r) for r in cur.fetchall()]


def update_escalation(escalation_id: int, status: str, staff_notes: str = None):
    """Change a case's status (and optionally its staff notes). Returns the updated row, or None.
    """
    if status not in ESCALATION_STATUSES:
        raise ValueError(f"status must be one of {ESCALATION_STATUSES}, got {status!r}")
    query = """
        UPDATE escalations
        SET status = %s,
            staff_notes = COALESCE(%s, staff_notes),
            resolved_at = CASE WHEN %s = 'resolved' THEN NOW() ELSE NULL END
        WHERE escalation_id = %s
        RETURNING *;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (status, staff_notes, status, escalation_id))
            row = cur.fetchone()
            conn.commit()
            return dict(row) if row else None


def close_conversation(conversation_id: int):
    """Mark an open chat as closed."""
    query = "UPDATE conversations SET status = 'closed' WHERE conversation_id = %s AND status = 'open';"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (conversation_id,))
            conn.commit()

def log_message(conversation_id: int, sender: str, content: str, intent: str = None,
                source: str = None, answer_type: str = None, details: dict = None,
                escalation_id: int = None) -> int:
    """Save one chat message with its audit details and return its id."""
    if sender not in ("customer", "assistant"):
        raise ValueError(f"sender must be 'customer' or 'assistant', got {sender!r}")
    # Details may hold Decimals or datetimes; a JSON round-trip with default=str makes them saveable.
    safe_details = json.loads(json.dumps(details, default=str)) if details is not None else None
    query = """
        INSERT INTO messages (conversation_id, sender, content, intent, source,
                              answer_type, details, escalation_id)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING message_id;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (conversation_id, sender, content, intent, source, answer_type,
                                Jsonb(safe_details) if safe_details is not None else None,
                                escalation_id))
            message_id = cur.fetchone()["message_id"]
            conn.commit()
            return message_id


def get_recent_turns(conversation_id: int, limit: int = 6):
    """The last `limit` messages of a chat, oldest first."""
    query = """
        SELECT * FROM (
            SELECT message_id, sender, content, intent, source, answer_type, details, created_at
            FROM messages WHERE conversation_id = %s
            ORDER BY message_id DESC LIMIT %s
        ) recent ORDER BY message_id;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (conversation_id, limit))
            return [dict(r) for r in cur.fetchall()]


def get_conversation_messages(conversation_id: int):
    """Every message of a chat, in order."""
    query = "SELECT * FROM messages WHERE conversation_id = %s ORDER BY message_id;"
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (conversation_id,))
            return [dict(r) for r in cur.fetchall()]


def list_conversations(limit: int = 20):
    """Most recent chats with message counts and the first customer question."""
    query = """
        SELECT c.conversation_id, c.status, c.started_at,
               COUNT(m.message_id) AS message_count,
               MAX(m.created_at) AS last_message_at,
               (ARRAY_AGG(m.content ORDER BY m.message_id)
                    FILTER (WHERE m.sender = 'customer'))[1] AS first_question
        FROM conversations c
        JOIN messages m ON m.conversation_id = c.conversation_id
        GROUP BY c.conversation_id
        ORDER BY MAX(m.created_at) DESC
        LIMIT %s;
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query, (limit,))
            return [dict(r) for r in cur.fetchall()]


if __name__ == "__main__":
    print("Product lookup (Hydra Balance):", get_product_by_name("Hydra Balance"))
    print("Price lookup (Niacinamide):", get_product_price("Niacinamide"))
    print("Availability (Niacinamide):", get_product_availability("Niacinamide"))
    print("Order lookup (GC10241):", get_order_status("GC10241"))
    print("Order lookup (GC99999, should be None):", get_order_status("GC99999"))
    print("Ingredients (GC-P001):", get_product_by_id("GC-P001")["ingredients"])
